import type { DynastyInfo } from '../types/dynasty';

export const xiaDynasty: DynastyInfo = {
  id: 'xia',
  name: '夏',
  fullName: '夏朝',
  period: '约前2070—前1600',
  duration: '约470年',
  capital: '阳城、斟鄩、安邑等',
  founder: '禹（启正式建国）',
  lastRuler: '桀',
  emperors: '14代17王',
  summary: '夏朝是中国史书记载的第一个世袭制王朝，由大禹奠基、夏启正式建立。夏朝标志着中国从部落联盟向早期国家转型，开创了"家天下"的王位世袭制，奠定了华夏文明的政治基础。二里头遗址被学术界普遍认为是夏代中晚期都城遗存。',
  highlights: [
    '大禹治水，三过家门而不入',
    '涂山之会，确立共主地位',
    '启废禅让，开创世袭"家天下"',
    '少康中兴，夏朝由乱转治',
    '二里头青铜礼器，华夏最早青铜文明',
    '鸣条之战，夏亡商兴',
  ],
  textbook: [
    {
      grade: '七上',
      unit: '第3课 远古的传说 / 第4课 夏商周的更替',
      keyPoints: [
        '约公元前2070年，禹建立夏朝，这是中国历史上第一个王朝',
        '禹死后，启继承父位，世袭制代替禅让制，"公天下"变为"家天下"',
        '夏朝建立了军队、刑法，制定了历法，还设置了监狱',
        '二里头遗址发现了宫殿建筑群、平民生活区和墓葬群，反映了阶级分化',
        '夏朝历经400多年，末代君主桀统治残暴，被商汤所灭',
      ],
      examFrequent: [
        '中国第一个王朝是夏朝（选择题高频）',
        '世袭制代替禅让制的标志：启继承父位（必背）',
        '"家天下"取代"公天下"始于启（高频考点）',
        '夏朝灭亡原因：桀的暴政',
        '二里头遗址反映了夏代的阶级分化和等级界限',
      ],
    },
  ],
  accent: {
    primary: '#c9a961',
    secondary: '#3a6b5c',
    watermark: '夏',
    subtitle: '青铜为礼 · 龙腾九州',
  },
  stats: [
    { label: '起止年份', value: '约前2070—前1600' },
    { label: '延续年数', value: '约470', unit: '年' },
    { label: '传承世代', value: '14', unit: '代' },
    { label: '君主数量', value: '17', unit: '王' },
  ],
  emperors_data: [
    {
      id: 1, name: '禹', alias: '夏禹、大禹、文命', reign: '约前2070-前2061',
      yearsOnThrone: 10, generation: 1, tag: 'founder',
      achievements: '继承父鲧治水事业，改"堵"为"疏"，历时十三年平定水患；划分天下为九州，铸造九鼎象征王权；涂山大会诸侯，万国来朝，确立共主地位。',
      evaluation: '夏朝奠基者。以治水之功获极高威望，被舜禅让为部落联盟首领，开启夏家天下之根基。三过家门而不入的精神传颂千古。',
      textbookPoints: ['大禹治水是夏朝建立的基础', '约前2070年建立夏朝，中国第一个王朝'],
    },
    {
      id: 2, name: '启', alias: '姒启', reign: '约前2057-前2019',
      yearsOnThrone: 39, generation: 2, tag: 'founder',
      achievements: '禹死后夺位，废除禅让制，正式建立夏朝，确立世袭王权；于甘地伐有扈氏，作《甘誓》激励将士，大获全胜；钓台之享确立"共主"地位。',
      evaluation: '家天下的开创者。"公天下"由此转变为"家天下"，是中国古代政治制度的重大变革，为后世封建君主专制奠定基础。',
      textbookPoints: ['★★★启继承父位，世袭制代替禅让制——必背高频考点', '"公天下"变为"家天下"始于启'],
    },
    {
      id: 3, name: '太康', reign: '约前2018-前1990',
      yearsOnThrone: 29, generation: 3, tag: 'lost',
      achievements: '继位后沉迷游猎，数月不归；东夷有穷氏首领后羿趁机攻占夏都斟鄩，太康失国流亡洛水之南。',
      evaluation: '失国之君。其荒淫无道导致夏朝政权中断数十年，是"荒政亡国"的典型教训。',
    },
    {
      id: 4, name: '仲康', reign: '约前1989-前1977',
      yearsOnThrone: 13, generation: 3, tag: 'lost',
      achievements: '太康之弟，后羿所立傀儡君主；实权操于后羿之手；曾借羲和氏荒废天时之机派兵征讨，试图夺回王权，未果。',
      evaluation: '傀儡之主。无力恢复夏室天下，在位期间形同虚设。',
    },
    {
      id: 5, name: '相', reign: '约前1976-前1949',
      yearsOnThrone: 28, generation: 4, tag: 'lost',
      achievements: '仲康之子，被寒浞追杀身死；其妻后缗怀少康逃归母族有仍氏，保存夏王室血脉。夏朝中断约40年。',
      evaluation: '乱世之君。在寒浞篡权中殉国，但其血脉延续了夏朝复国的希望。',
    },
    {
      id: 6, name: '少康', reign: '约前1908-前1888',
      yearsOnThrone: 21, generation: 5, tag: 'restore',
      achievements: '相之遗腹子，流亡中有虞氏庇护；联络夏朝旧臣靡，派女艾为间谍刺探寒浞之子浇情报；最终诛杀寒浞，夺回政权，史称"少康中兴"。',
      evaluation: '中兴之主。夏朝由乱转治的转折点，展现了坚韧不拔的意志与卓越领导才能，使夏朝重新走向繁荣。',
    },
    {
      id: 7, name: '杼', alias: '予、季杼', reign: '约前1887-前1871',
      yearsOnThrone: 17, generation: 6, tag: 'golden',
      achievements: '少康之子，发明甲和矛；大举征伐东夷，取得胜利，使夏朝达到鼎盛；被后世历代夏王尊称为"圣主"。',
      evaluation: '鼎盛之君。军事创新与征伐使夏朝国力空前强大，是夏朝最强盛时期的代表。',
    },
    {
      id: 8, name: '槐', alias: '芬', reign: '约前1870-前1845',
      yearsOnThrone: 26, generation: 7, tag: 'golden',
      achievements: '杼之子，在位时社会经济有所发展；九夷全来朝贡，是史上第一位达成此成就的夏王。',
      evaluation: '守成之君。延续父亲鼎盛局面，四方来朝，国势稳定。',
    },
    {
      id: 9, name: '芒', alias: '荒', reign: '约前1844-前1787',
      yearsOnThrone: 58, generation: 8, tag: 'normal',
      achievements: '槐之子，始行"沉祭"——将祭物沉入黄河企求河神庇护，此仪式延续数千年。',
      evaluation: '仪式开创者。沉祭传统影响深远，但其在位长久，事迹记载较少。',
    },
    {
      id: 10, name: '泄', reign: '约前1786-前1765',
      yearsOnThrone: 22, generation: 9, tag: 'normal',
      achievements: '芒之子，正式册封畎夷、白夷等九夷部落诸侯爵位，加强夏朝与周边部落联系，扩大宗主权威。',
      evaluation: '怀柔之君。通过册封巩固对东方夷人的影响力，维护王朝秩序。',
    },
    {
      id: 11, name: '不降', reign: '约前1764-前1706',
      yearsOnThrone: 59, generation: 10, tag: 'normal',
      achievements: '泄之子，夏朝在位时间最长的君主；在位期间和平治世，晚年主动让位给弟弟扃，传为美谈。',
      evaluation: '仁德之君。在位最久且主动禅让，是夏朝中期的明君典范。',
    },
    {
      id: 12, name: '扃', alias: '局、禺', reign: '约前1745-前1725',
      yearsOnThrone: 21, generation: 10, tag: 'normal',
      achievements: '不降之弟，继兄位；在位期间平稳传承，维护夏朝稳定。',
      evaluation: '平稳之君。承兄之治，无大功亦无大过。',
    },
    {
      id: 13, name: '廑', alias: '胤甲', reign: '约前1724-前1705',
      yearsOnThrone: 20, generation: 11, tag: 'normal',
      achievements: '扃之子，在位时夏国开始衰落；天象异常，迁都西河。',
      evaluation: '转衰之君。夏朝国势自此初显颓势。',
    },
    {
      id: 14, name: '孔甲', reign: '约前1704-前1674',
      yearsOnThrone: 31, generation: 11, tag: 'tyrant',
      achievements: '不降之子，性好鬼神，沉湎酒色；任用奸佞，朝政腐败，民不聊生；传说曾让刘累为其驯龙。',
      evaluation: '乱政之君。司马迁评"帝孔甲立，好方鬼神，事淫乱"。诸侯纷纷叛离，夏朝国势急剧衰退，为商汤灭夏埋下伏笔。',
    },
    {
      id: 15, name: '皋', alias: '昊、皋茍', reign: '约前1673-前1671',
      yearsOnThrone: 3, generation: 12, tag: 'normal',
      achievements: '孔甲之子，在位短暂，无力扭转颓势。',
      evaluation: '过渡之君。夏朝衰落已不可逆。',
    },
    {
      id: 16, name: '发', alias: '发惠', reign: '约前1670-前1652',
      yearsOnThrone: 19, generation: 13, tag: 'normal',
      achievements: '皋之子，破格提拔关龙逄为相，试图振作；但各方诸侯已不来朝贺，夏国进一步衰落。',
      evaluation: '回天乏术之君。虽有贤臣辅佐，但大厦将倾，已无力回天。',
    },
    {
      id: 17, name: '桀', alias: '履癸、癸', reign: '约前1651-前1600',
      yearsOnThrone: 52, generation: 14, tag: 'tyrant',
      achievements: '发之子，末代君主。文武双全，赤手可拉直铁钩，却荒淫无度、暴虐嗜杀；建酒池肉林，残杀忠臣关龙逢；鸣条之战被商汤击败，流放南巢病死，夏朝灭亡。',
      evaluation: '亡国之君。穷奢极欲，暴政激变，终于在前1600年鸣条之战中亡国。"桀"为商汤所上谥号，意为凶猛。是后世"暴君"的代名词。',
      textbookPoints: ['★★★桀是暴君典型，夏朝灭亡于桀的暴政——高频考点'],
    },
  ],
  events_data: [
    {
      id: 1, title: '大禹治水', time: '约公元前2070年前', icon: '水', category: 'culture',
      summary: '禹继承父鲧治水事业，改"堵"为"疏"，历时十三年平定水患，划定九州。',
      details: '尧舜时代，中原洪水泛滥，百姓苦不堪言。禹父鲧采用"堵"法治水失败被杀。禹继父业，吸取教训，改用"疏导"之法——高处凿通，低处疏导，使洪水流入海洋；同时疏通田间沟渠，引水灌溉。治水过程中禹三过家门而不入，历时十三年终成大功。禹走遍天下，详查各地地形、习俗、物产，重新划分九州，设立五服贡赋体系。',
      impact: '治水成功不仅解除了洪水威胁，使百姓安居乐业，更促进了农业发展，为夏朝建立奠定经济基础。禹因功获极高威望，被舜禅让为部落联盟首领，为夏朝建立奠定政治基础。',
      figures: ['禹', '鲧', '舜', '伯益', '后稷'],
      textbookPoints: ['大禹治水采用疏导方法', '三过家门而不入体现了公而忘私的精神'],
    },
    {
      id: 2, title: '涂山之会', time: '约公元前2070年', icon: '盟', category: 'founding',
      summary: '禹在涂山大会诸侯，万国来朝，确立共主地位，象征夏朝政权初步形成。',
      details: '大禹治水成功后，在涂山（今安徽蚌埠怀远县境内）召集天下诸侯举行盟会。各方诸侯纷纷前来，带着玉帛等礼品朝见大禹。大禹在会上检讨自己过失，让诸侯指出不足，同时展示治水成果，颁布各项法令。晚年又会诸侯于会稽山，防风氏迟到被诛杀，树立王权绝对权威。传说禹铸造九鼎，象征统一天下九州万国。',
      impact: '涂山之会是夏朝建立的标志性事件。大禹的权威得到众多部落首领认可，夏朝国家政权初步形成，也促进了各地文化经济交流融合，推动了夏朝文明发展。',
      figures: ['禹', '防风氏'],
      textbookPoints: ['涂山之会是夏朝建立的标志'],
    },
    {
      id: 3, title: '启建夏朝·甘之战', time: '约公元前2057年', icon: '战', category: 'founding',
      summary: '启废禅让立世袭，开创"家天下"；有扈氏不服，启作《甘誓》伐之，大胜。',
      details: '禹死后按禅让制本应由伯益继位，但禹之子启凭借实力威望夺权，废除禅让制，确立世袭王权。同姓有扈氏部落公然反对，启召集军队讨伐，双方大战于甘地（今郑州西北古荥泽之外）。战前启发布雄壮的《尚书·甘誓》激励将士："用命，赏于祖；不用命，戮于社。"启军战术精湛、纪律严明，最终大获全胜。此后启又在都城阳翟钓台举行盛大献祭活动，确立"共主"地位。',
      impact: '王位世袭制的确立是中国古代政治制度的重大变革。"公天下"转为"家天下"，国家权力高度集中于一家一姓，为中国封建君主专制制度形成奠定基础。甘之战的胜利进一步巩固了启的统治。',
      figures: ['启', '伯益', '有扈氏'],
      textbookPoints: ['★★★世袭制代替禅让制，"公天下"变"家天下"——必背'],
    },
    {
      id: 4, title: '太康失国', time: '约公元前2018年', icon: '失', category: 'disaster',
      summary: '太康沉迷游猎，后羿趁机夺夏都斟鄩，夏朝政权中断数十年。',
      details: '启之子太康继位后，沉湎享乐，不理政事，经常外出打猎数月不归。东夷有穷氏首领后羿（善射，非神话中射日之后羿）趁机起兵，攻占夏都斟鄩（今河南洛阳偃师二里头）。太康失去王位，被迫逃奔洛水之南，史称"太康失国"。后羿立太康之弟仲康为傀儡君主，实权操于后羿之手。仲康死后其子相继位，后被后羿家臣寒浞追杀，夏朝中断约40年。',
      impact: '太康失国标志着夏朝内部矛盾激化和统治衰落，反映了统治者荒淫无道可能导致的严重后果，为后世提供深刻历史教训。夏朝由此进入最动荡时期。',
      figures: ['太康', '后羿', '仲康', '相', '寒浞'],
    },
    {
      id: 5, title: '少康中兴', time: '约公元前1908年', icon: '兴', category: 'prosperity',
      summary: '少康诛杀寒浞复国，夏朝由乱转治，是夏朝历史的重要转折点。',
      details: '后羿篡权后亦沉迷游猎，被亲信寒浞所杀，寒浞自立为王，追杀夏后氏后裔。相之妻后缗怀少康逃归母族有仍氏，生下少康。少康在有虞氏部落得到庇护，长大后勤勉积蓄力量，联络夏朝旧臣靡，联合有鬲氏。少康派女艾作为间谍混入寒浞之子浇身边刺探情报，又令其子季抒诛杀寒浞另一子豷，最终攻杀寒浞，夺回政权。少康继位后励精图治，整顿内政，发展经济，使夏朝重新走向繁荣。',
      impact: '少康中兴是夏朝历史的重要转折点，使夏朝在经历动荡衰落后重新走向繁荣昌盛，巩固了夏朝统治地位。少康坚韧不拔的意志和卓越领导才能，成为后世"中兴复国"的典范。',
      figures: ['少康', '寒浞', '后缗', '靡', '女艾', '季抒'],
    },
    {
      id: 6, title: '孔甲乱政', time: '约公元前1704年', icon: '乱', category: 'disaster',
      summary: '孔甲好鬼神、沉酒色，诸侯离心背叛，夏朝国势急剧衰退。',
      details: '少康中兴后夏朝曾有一段稳定期，但到孔甲时期情况恶化。孔甲迷信鬼神，沉湎享乐，对朝政不闻不问，任用奸佞之臣，导致朝政腐败、民不聊生、社会矛盾尖锐。传说孔甲曾让刘累为其驯龙，刘累因驯养失误惧祸逃亡鲁县（刘氏始祖之一）。司马迁评："帝孔甲立，好方鬼神，事淫乱。"诸侯纷纷叛离，夏朝再次陷入混乱衰落。',
      impact: '孔甲乱政加速了夏朝的衰落，国力和威望受到严重削弱，诸侯背叛、百姓怨声载道，为后来商汤灭夏埋下伏笔。是夏朝由盛转衰的关键节点。',
      figures: ['孔甲', '刘累'],
    },
    {
      id: 7, title: '鸣条之战', time: '约公元前1600年', icon: '灭', category: 'fall',
      summary: '商汤在伊尹辅佐下于鸣条击败夏桀，夏朝灭亡，商朝建立。',
      details: '夏朝末代君主桀荒淫无度、暴虐嗜杀，建酒池肉林，残杀忠臣关龙逢，百姓生活在水深火热之中。商族在首领汤的领导下逐渐强大，汤在大臣伊尹辅佐下，先后灭掉葛国、韦国、顾国、昆吾国等夏朝属国，剪除夏朝羽翼。夏桀曾将商汤囚禁于夏台，后释放。商汤积蓄力量后正式兴兵伐桀，两军在鸣条（今河南封丘东）展开激战。商军士气高昂、作战勇猛，夏军兵败如山倒，夏桀率残军逃奔南巢（今安徽巢湖西南），不久病死，夏朝灭亡。商汤建立商朝。',
      impact: '鸣条之战是中国历史上一次重要战争，标志着夏朝结束和商朝建立，是古代王朝更替的重要事件，反映了王朝兴衰的必然性——得民心者得天下，失民心者失天下。',
      figures: ['桀', '商汤', '伊尹', '关龙逢'],
      textbookPoints: ['★★★约前1600年，商汤灭夏，商朝建立——必背', '夏朝灭亡原因：桀的暴政', '鸣条之战：商汤击败夏桀'],
    },
  ],
  artifacts_data: [
    {
      id: 1, name: '绿松石龙形器', era: '二里头文化 距今约3800年',
      unearthed: '2002年二里头遗址VT15M3', material: '绿松石、白玉、青铜',
      summary: '"华夏第一龙"，由2000余片绿松石拼嵌而成，中国早期龙形象文物中最精美、体量最大的一件。',
      description: '2002年春出土于二里头遗址3号宫殿基址的贵族墓葬。龙身长64.5厘米，中部最宽处4厘米，由2000余片各种形状的绿松石片组合而成，每片长0.2-0.9厘米，厚约0.1厘米。龙头置于绿松石片粘嵌的梯形托座上，以三节实心半圆形青、白玉柱组成额面中脊和鼻梁，绿松石蒜头状鼻端硕大醒目，眼眶中以圆饼形白玉为睛。龙身由12组菱形图案组成鳞纹，连续分布于全身，龙脊中线两侧饰片倒角处理，形成棱角分明的脊背线条。放置于墓主人骨架之上，头朝西北，尾向东南。龙身中部镶嵌青铜铃铛，与《诗经》"龙旂阳阳，和铃央央"祭祀场景遥相呼应。',
      significance: '证明了早在夏代先民已把龙作为图腾崇拜，学术界普遍认为是华夏龙图腾最直接、最正统的根源，是华夏儿女作为"龙的传人"的最初起源和有力实证。其梭形眼、菱形额饰、波状身躯等特征直接影响了商周青铜器饕餮纹与龙纹，成为华夏龙形象的标准范式。被誉为"华夏第一龙""中华第一龙"。',
      imageUrl: 'https://console.enterprise.trae.cn/api/ide/v1/text_to_image?prompt=Chinese%20national%20treasure%20turquoise%20dragon-shaped%20artifact%20from%20Erlitou%20site%2C%20ancient%20Xia%20dynasty%2C%202000%20turquoise%20pieces%20inlaid%20into%20a%2064.5cm%20long%20dragon%20with%20white%20jade%20eyes%2C%20dark%20museum%20background%20with%20dramatic%20lighting%2C%20bronze%20green%20and%20gold%20tones%2C%20archaeological%20photography%20style&image_size=landscape_4_3',
      tag: 'national-treasure', location: '中国社会科学院考古研究所',
      textbookPoints: ['二里头遗址出土的绿松石龙形器被誉为"华夏第一龙"', '证明夏代已有龙图腾崇拜'],
    },
    {
      id: 2, name: '嵌绿松石兽面纹铜牌饰', era: '约公元前1700-前1500年',
      unearthed: '二里头遗址贵族墓葬', material: '青铜、绿松石',
      summary: '青铜铸造框架与绿松石镶嵌工艺，单片绿松石厚仅1-2毫米，历经3500年未脱落，将中国青铜镶嵌工艺提前千余年。',
      description: '长约15厘米、宽不足10厘米，采用青铜铸造框架与绿松石镶嵌工艺制成。单片绿松石厚度仅1-2毫米，历经3500年未脱落，工艺之精湛令人叹为观止。兽面纹饰被推测为早期龙形象，与同期出土的绿松石龙形器共同构成夏代阶级分化的物证。',
      significance: '将中国青铜镶嵌工艺出现时间提前了1000余年。是商周青铜器兽面纹装饰的先驱，通过纹饰关联反映了中原与西北、西南地区的早期文明交流，是研究夏代礼制与早期文明交流的重要实物。',
      imageUrl: 'https://console.enterprise.trae.cn/api/ide/v1/text_to_image?prompt=Chinese%20ancient%20bronze%20plaque%20inlaid%20with%20turquoise%20animal%20mask%20pattern%20from%20Erlitou%20Xia%20dynasty%2C%2015cm%20wide%2C%20intricate%20turquoise%20inlay%20forming%20taotie%20mask%20design%2C%20dark%20museum%20exhibition%20lighting%2C%20green%20patina%20and%20gold%20turquoise%2C%20archaeological%20treasure&image_size=landscape_4_3',
      tag: 'bronze', location: '二里头夏都遗址博物馆等',
    },
    {
      id: 3, name: '青铜爵', era: '二里头文化 距今约3700年',
      unearthed: '二里头遗址', material: '青铜',
      summary: '二里头文化典型酒器，中国早期青铜礼器代表，标志着青铜礼器时代的开启。',
      description: '二里头出土的青铜爵是目前已知中国最早的青铜礼器之一。器形为典型的饮酒器：前有流（倾酒的槽），后有尾，中部为杯腹，一侧有鋬（把手），下有三足。器壁较薄，铸造工艺已相当成熟。这种青铜爵是夏代贵族礼仪活动的重要礼器，体现了早期国家礼制雏形。',
      significance: '标志着中国青铜礼器时代的开启，是研究中国早期青铜铸造技术和礼制形成的关键实物。从陶爵到青铜爵的演变，反映了夏代社会从部落联盟向早期国家的转型。',
      imageUrl: 'https://console.enterprise.trae.cn/api/ide/v1/text_to_image?prompt=Chinese%20ancient%20bronze%20jue%20wine%20vessel%20from%20Erlitou%20Xia%20dynasty%2C%20three-legged%20drinking%20cup%20with%20long%20spout%20and%20handle%2C%20green%20patina%20bronze%2C%20dark%20museum%20background%2C%20dramatic%20side%20lighting%2C%20archaeological%20photography&image_size=landscape_4_3',
      tag: 'bronze',
      textbookPoints: ['二里头遗址出土的青铜爵是中国最早的青铜礼器之一', '青铜礼器的出现是早期国家形成的标志'],
    },
    {
      id: 4, name: '七孔玉刀', era: '二里头文化 距今约3700年',
      unearthed: '二里头遗址', material: '玉',
      summary: '二里头出土的大型玉礼器，七孔设计独特，是夏代玉器工艺的代表作。',
      description: '大型玉制礼器，刀形器身钻有七个圆孔，故称"七孔玉刀"。玉质温润，工艺精湛，器身修长，刃部锋利但未见实用痕迹，表明其为礼仪用器而非实用工具。七孔的设计可能具有特殊的礼制或象征意义。此刀出土于高等级墓葬，是墓主贵族身份地位的象征。',
      significance: '是研究夏代玉器工艺和礼制的重要实物。大型玉礼器的出现，反映了二里头文化时期社会分化的加剧和礼制的形成，为研究中国早期玉文化提供了关键资料。',
      imageUrl: 'https://console.enterprise.trae.cn/api/ide/v1/text_to_image?prompt=Chinese%20ancient%20jade%20knife%20with%20seven%20holes%20from%20Erlitou%20Xia%20dynasty%2C%20large%20ritual%20jade%20blade%2C%20translucent%20pale%20green%20jade%2C%20museum%20dark%20background%2C%20soft%20museum%20lighting%2C%20archaeological%20treasure%20photography&image_size=landscape_4_3',
      tag: 'jade',
    },
    {
      id: 5, name: '陶盉', era: '二里头文化 距今约3700年',
      unearthed: '二里头遗址', material: '陶土',
      summary: '二里头文化典型陶器，夏代日常礼器与生活用器的代表，反映制陶工艺水平。',
      description: '二里头文化最具代表性的陶器之一。器形为三足封顶盉：顶部封闭，前有管状流，后有鋬，下有三袋足。此种设计既可盛酒又可温酒，是夏代贵族礼仪与日常生活的重要器物。陶盉的形制后来影响了青铜盉的设计。',
      significance: '是研究夏代日常生活与礼制的重要实物。陶盉从生活用器到礼器的演变，体现了二里头文化时期礼制的形成过程，为理解中国早期礼乐文明提供了重要线索。',
      imageUrl: 'https://console.enterprise.trae.cn/api/ide/v1/text_to_image?prompt=Chinese%20ancient%20pottery%20he%20vessel%20from%20Erlitou%20Xia%20dynasty%2C%20three-legged%20pottery%20wine%20warmer%20with%20spout%20and%20handle%2C%20earthen%20brown%20color%2C%20museum%20dark%20background%2C%20archaeological%20exhibit%20photography&image_size=landscape_4_3',
      tag: 'pottery',
    },
  ],
  quiz_data: [
    {
      id: 1, question: '夏朝是中国历史上第一个什么制的王朝？',
      options: ['禅让制', '世袭制', '封建制', '郡县制'], correctIndex: 1,
      explanation: '夏启废除禅让制，确立世袭制，开启"家天下"局面，是中国历史上第一个世袭制王朝。',
      difficulty: 'easy', textbookSource: '七上第4课',
    },
    {
      id: 2, question: '大禹治水采用的主要方法是什么？',
      options: ['堵截法', '疏导法', '填埋法', '分流法'], correctIndex: 1,
      explanation: '禹吸取父鲧"堵"法失败的教训，改用"疏导"之法——高处凿通，低处疏导，使洪水归流入海。',
      difficulty: 'easy', textbookSource: '七上第3课',
    },
    {
      id: 3, question: '"华夏第一龙"绿松石龙形器出土于哪个遗址？',
      options: ['殷墟', '二里头遗址', '良渚遗址', '红山遗址'], correctIndex: 1,
      explanation: '2002年绿松石龙形器出土于河南洛阳偃师二里头遗址，由2000余片绿松石拼嵌而成，被誉为"华夏第一龙"。',
      difficulty: 'medium', textbookSource: '七上第4课',
    },
    {
      id: 4, question: '夏朝共传多少代多少位君主？',
      options: ['14代17王', '13代16王', '15代18王', '12代15王'], correctIndex: 0,
      explanation: '据《史记·夏本纪》和古本《竹书纪年》记载，夏朝自禹至桀共传14代17王，历时约470年。',
      difficulty: 'medium',
    },
    {
      id: 5, question: '鸣条之战中击败夏桀、建立商朝的是谁？',
      options: ['商纣', '商汤', '盘庚', '武丁'], correctIndex: 1,
      explanation: '约前1600年，商汤在伊尹辅佐下于鸣条之战击败夏桀，夏朝灭亡，商朝建立。',
      difficulty: 'easy', textbookSource: '七上第4课',
    },
    {
      id: 6, question: '夏朝由乱转治的重要转折点是？',
      options: ['太康失国', '少康中兴', '孔甲乱政', '涂山之会'], correctIndex: 1,
      explanation: '少康诛杀寒浞复国，励精图治使夏朝重新走向繁荣，史称"少康中兴"，是夏朝由乱转治的转折点。',
      difficulty: 'medium',
    },
  ],
};
